<script setup lang="ts">
  import { Search, X, Hash, FileText, CornerDownLeft } from 'lucide-vue-next'

  // Pagefind static-search integration. The index is generated by
  // `pnpm build` (which runs `pagefind --site .output/public` after
  // `nuxi build`) and ships as `_pagefind/` next to the rest of the
  // static output. At runtime, this component dynamically imports
  // `/_pagefind/pagefind.js` and queries against its bundled index —
  // entirely client-side, no backend.
  //
  // In dev (`nuxi dev`), `_pagefind/` doesn't exist yet, so the
  // dynamic import 404s. We catch that and surface a friendly
  // "search becomes available after build" message; the trigger
  // button stays interactive so the rest of the keyboard /
  // navigation UX can be exercised.

  type PagefindSubResult = {
    title: string
    url: string
    excerpt: string
  }
  type PagefindResultData = {
    url: string
    excerpt: string
    meta: { title?: string }
    sub_results?: PagefindSubResult[]
  }
  type PagefindModule = {
    options: (opts: Record<string, unknown>) => Promise<void>
    search: (query: string) => Promise<{
      results: Array<{ id: string; data: () => Promise<PagefindResultData> }>
    }>
  }

  type SearchHit = {
    url: string
    pageTitle: string
    sectionTitle: string | null
    excerpt: string
  }

  const open = ref(false)
  const query = ref('')
  const hits = ref<SearchHit[]>([])
  const activeIndex = ref(0)
  const loading = ref(false)
  const status = ref<'idle' | 'empty' | 'unavailable' | 'error' | 'ready'>('idle')

  const inputRef = ref<HTMLInputElement | null>(null)
  const listRef = ref<HTMLElement | null>(null)
  let pagefind: PagefindModule | null = null
  let loadAttempted = false
  let debounceTimer: ReturnType<typeof setTimeout> | undefined

  const router = useRouter()

  // Lazily fetch the Pagefind runtime + bundled index. `@vite-ignore`
  // tells Vite not to try to resolve this static-asset path at build
  // time — we want the browser to fetch it from the deployed origin.
  async function loadPagefind(): Promise<PagefindModule | null> {
    if (pagefind) return pagefind
    if (loadAttempted) return null
    loadAttempted = true
    try {
      const path = '/_pagefind/pagefind.js'
      const mod = (await import(/* @vite-ignore */ path)) as PagefindModule
      await mod.options({ excerptLength: 25 })
      pagefind = mod
      return pagefind
    } catch {
      status.value = 'unavailable'
      return null
    }
  }

  // Pagefind returns one result per page, with `sub_results` for
  // each h2/h3 that matched. Flatten those into individual rows so
  // a single page can surface multiple section hits — that's the
  // pattern users expect from docs search ("typeahead jumps me to
  // the right section, not just the right page").
  function flattenResults(rawResults: PagefindResultData[]): SearchHit[] {
    const out: SearchHit[] = []
    for (const r of rawResults) {
      const pageTitle = r.meta.title?.trim() || 'Documentation'
      if (r.sub_results && r.sub_results.length > 0) {
        for (const sub of r.sub_results.slice(0, 3)) {
          out.push({
            url: sub.url,
            pageTitle,
            sectionTitle: sub.title,
            excerpt: sub.excerpt,
          })
        }
      } else {
        out.push({
          url: r.url,
          pageTitle,
          sectionTitle: null,
          excerpt: r.excerpt,
        })
      }
    }
    return out
  }

  async function performSearch() {
    const q = query.value.trim()
    if (!q) {
      hits.value = []
      status.value = 'idle'
      return
    }
    loading.value = true
    const pf = await loadPagefind()
    if (!pf) {
      // status.value already set to 'unavailable' inside loadPagefind
      loading.value = false
      hits.value = []
      return
    }
    try {
      const result = await pf.search(q)
      const rawData = await Promise.all(result.results.slice(0, 6).map((r) => r.data()))
      hits.value = flattenResults(rawData).slice(0, 12)
      activeIndex.value = 0
      status.value = hits.value.length > 0 ? 'ready' : 'empty'
    } catch {
      status.value = 'error'
      hits.value = []
    } finally {
      loading.value = false
    }
  }

  watch(query, () => {
    if (debounceTimer) clearTimeout(debounceTimer)
    debounceTimer = setTimeout(performSearch, 180)
  })

  // Open / close lifecycle: lock body scroll, focus the input,
  // reset state on close.
  watch(open, async (isOpen) => {
    if (typeof document === 'undefined') return
    if (isOpen) {
      document.body.style.overflow = 'hidden'
      await nextTick()
      inputRef.value?.focus()
    } else {
      document.body.style.overflow = ''
      query.value = ''
      hits.value = []
      activeIndex.value = 0
      status.value = 'idle'
    }
  })

  function close() {
    open.value = false
  }

  function selectHit(hit: SearchHit) {
    router.push(hit.url)
    close()
  }

  function onModalKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape') {
      e.preventDefault()
      close()
      return
    }
    if (hits.value.length === 0) return
    if (e.key === 'ArrowDown') {
      e.preventDefault()
      activeIndex.value = (activeIndex.value + 1) % hits.value.length
      scrollActiveIntoView()
    } else if (e.key === 'ArrowUp') {
      e.preventDefault()
      activeIndex.value = (activeIndex.value - 1 + hits.value.length) % hits.value.length
      scrollActiveIntoView()
    } else if (e.key === 'Enter') {
      e.preventDefault()
      const hit = hits.value[activeIndex.value]
      if (hit) selectHit(hit)
    }
  }

  function scrollActiveIntoView() {
    nextTick(() => {
      const el = listRef.value?.querySelector<HTMLElement>('[data-active="true"]')
      el?.scrollIntoView({ block: 'nearest' })
    })
  }

  // ⌘K (Mac) / Ctrl+K (rest) opens the modal from anywhere.
  // `/` also opens — common docs convention. Don't intercept either
  // when a text input / textarea / contenteditable is focused (we
  // don't want to swallow the user's typing in the REPL).
  function onGlobalKeydown(e: KeyboardEvent) {
    const target = e.target as HTMLElement | null
    const isTyping =
      target &&
      (target.tagName === 'INPUT' || target.tagName === 'TEXTAREA' || target.isContentEditable)

    const isShortcutModifier = e.metaKey || e.ctrlKey
    if (isShortcutModifier && e.key === 'k') {
      e.preventDefault()
      open.value = true
      return
    }
    if (e.key === '/' && !isTyping && !open.value) {
      e.preventDefault()
      open.value = true
    }
  }

  onMounted(() => {
    window.addEventListener('keydown', onGlobalKeydown)
  })
  onUnmounted(() => {
    window.removeEventListener('keydown', onGlobalKeydown)
    if (typeof document !== 'undefined') document.body.style.overflow = ''
  })

  // Surface the right modifier glyph based on platform — ⌘ on macOS,
  // Ctrl elsewhere. SSR fallback uses ⌘ since both render the same
  // width and Mac is the dominant dev platform.
  const isMac = ref(true)
  onMounted(() => {
    isMac.value = /Mac|iPhone|iPad/i.test(navigator.platform || navigator.userAgent || '')
  })
</script>

<template>
  <!-- Trigger — wide button on md+ that mimics a search field, then
       collapses to icon-only on small viewports so it fits next to
       the rest of the header chrome without crowding. -->
  <button
    type="button"
    aria-label="Search documentation"
    class="group inline-flex h-9 items-center gap-2 rounded-md border border-border bg-bg pr-1.5 pl-3 text-sm text-fg-muted shadow-xs transition-colors duration-(--duration-fast) hover:border-border-strong hover:text-fg focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-accent-ring md:w-56"
    @click="open = true"
  >
    <Search class="h-4 w-4 shrink-0" :stroke-width="2" />
    <span class="hidden md:inline">Search docs</span>
    <kbd
      class="ml-auto hidden h-5 items-center rounded border border-border bg-surface px-1.5 font-mono text-[0.6875rem] text-fg-subtle md:inline-flex"
      aria-hidden="true"
    >
      <span v-if="isMac">⌘</span><span v-else>Ctrl</span>K
    </kbd>
  </button>

  <Teleport to="body">
    <Transition
      enter-from-class="opacity-0"
      enter-active-class="transition-opacity duration-(--duration-base) ease-(--ease-out-quart)"
      enter-to-class="opacity-100"
      leave-from-class="opacity-100"
      leave-active-class="transition-opacity duration-(--duration-fast) ease-(--ease-out-quart)"
      leave-to-class="opacity-0"
    >
      <div
        v-if="open"
        class="fixed inset-0 z-50 bg-fg/40 backdrop-blur-sm"
        aria-hidden="true"
        @click="close"
      />
    </Transition>
    <Transition
      enter-from-class="opacity-0 translate-y-2 scale-[0.98]"
      enter-active-class="transition-[opacity,transform] duration-(--duration-base) ease-(--ease-out-quart)"
      enter-to-class="opacity-100 translate-y-0 scale-100"
      leave-from-class="opacity-100 translate-y-0 scale-100"
      leave-active-class="transition-[opacity,transform] duration-(--duration-fast) ease-(--ease-out-quart)"
      leave-to-class="opacity-0 translate-y-2 scale-[0.98]"
    >
      <div
        v-if="open"
        role="dialog"
        aria-modal="true"
        aria-label="Search documentation"
        class="fixed inset-0 z-50 flex items-start justify-center px-4 pt-[10vh]"
        @keydown="onModalKeydown"
      >
        <div
          class="flex max-h-[80vh] w-full max-w-xl flex-col overflow-hidden rounded-xl border bg-bg shadow-2xl"
          @click.stop
        >
          <!-- Search input row -->
          <div class="flex h-14 items-center gap-3 border-b border-border px-4">
            <Search class="h-5 w-5 shrink-0 text-fg-muted" :stroke-width="2" />
            <input
              ref="inputRef"
              v-model="query"
              type="text"
              autocomplete="off"
              autocorrect="off"
              autocapitalize="off"
              spellcheck="false"
              placeholder="Search the documentation…"
              class="flex-1 bg-transparent text-base text-fg placeholder:text-fg-subtle focus:outline-none"
            />
            <button
              type="button"
              aria-label="Close search"
              class="inline-flex h-7 w-7 items-center justify-center rounded-md text-fg-muted transition-colors duration-(--duration-fast) hover:bg-surface hover:text-fg"
              @click="close"
            >
              <X class="h-4 w-4" :stroke-width="2" />
            </button>
          </div>

          <!-- Results / status panel -->
          <div ref="listRef" class="flex-1 overflow-y-auto">
            <div v-if="status === 'idle'" class="px-4 py-10 text-center text-sm text-fg-muted">
              Type to search the docs.
            </div>
            <div
              v-else-if="status === 'unavailable'"
              class="px-4 py-10 text-center text-sm text-fg-muted"
            >
              <p class="font-medium text-fg">Search index not built yet</p>
              <p class="mt-1.5">
                Run
                <code class="rounded bg-surface px-1.5 py-0.5 font-mono text-xs"
                  >pnpm build:site</code
                >
                to generate the search index.
              </p>
            </div>
            <div
              v-else-if="status === 'empty'"
              class="px-4 py-10 text-center text-sm text-fg-muted"
            >
              No results for
              <span class="font-medium text-fg">"{{ query }}"</span>.
            </div>
            <div v-else-if="status === 'error'" class="px-4 py-10 text-center text-sm text-danger">
              Something went wrong. Try again.
            </div>
            <ul v-else class="py-2">
              <li v-for="(hit, i) in hits" :key="`${hit.url}-${i}`">
                <button
                  type="button"
                  :data-active="i === activeIndex"
                  class="flex w-full items-start gap-3 px-4 py-2.5 text-left transition-colors duration-(--duration-fast) data-[active=true]:bg-accent-soft"
                  @mouseenter="activeIndex = i"
                  @click="selectHit(hit)"
                >
                  <div
                    class="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-md border border-border bg-bg text-fg-muted"
                  >
                    <Hash v-if="hit.sectionTitle" class="h-3.5 w-3.5" :stroke-width="2.25" />
                    <FileText v-else class="h-3.5 w-3.5" :stroke-width="2" />
                  </div>
                  <div class="min-w-0 flex-1">
                    <div class="flex items-center gap-1.5 text-sm font-semibold text-fg">
                      <span class="truncate">{{ hit.sectionTitle ?? hit.pageTitle }}</span>
                    </div>
                    <p
                      v-if="hit.sectionTitle"
                      class="text-xs font-medium text-fg-subtle uppercase tracking-wide"
                    >
                      {{ hit.pageTitle }}
                    </p>
                    <!-- eslint-disable-next-line vue/no-v-html — Pagefind returns excerpts wrapped in <mark> tags from content we control (the docs corpus); rendering as HTML lets us style the highlighted matches via the [&_mark] selector. -->
                    <p
                      class="mt-1 line-clamp-2 text-sm text-fg-muted [&_mark]:bg-transparent [&_mark]:font-semibold [&_mark]:text-accent"
                      v-html="hit.excerpt"
                    />
                  </div>
                  <CornerDownLeft
                    v-if="i === activeIndex"
                    class="mt-1 h-3.5 w-3.5 shrink-0 text-fg-subtle"
                    :stroke-width="2.25"
                  />
                </button>
              </li>
            </ul>
          </div>

          <!-- Keyboard hints footer -->
          <div
            class="flex h-10 items-center gap-4 border-t border-border bg-surface/60 px-4 text-xs text-fg-subtle"
          >
            <span class="flex items-center gap-1.5">
              <kbd class="kbd">↑</kbd><kbd class="kbd">↓</kbd>
              <span>navigate</span>
            </span>
            <span class="flex items-center gap-1.5">
              <kbd class="kbd">↵</kbd>
              <span>select</span>
            </span>
            <span class="flex items-center gap-1.5">
              <kbd class="kbd">esc</kbd>
              <span>close</span>
            </span>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<style scoped>
  .kbd {
    display: inline-flex;
    height: 1.125rem;
    min-width: 1.125rem;
    align-items: center;
    justify-content: center;
    padding: 0 0.3125rem;
    border: 0.0625rem solid var(--color-border);
    background: var(--color-bg);
    border-radius: 0.25rem;
    font-family: var(--font-mono);
    font-size: 0.6875rem;
    color: var(--color-fg-muted);
  }
</style>
