import { addImports, addPluginTemplate, addTypeTemplate, defineNuxtModule } from '@nuxt/kit'
import { inputTextAreaNodeTransform } from './runtime/lib/core/transforms/input-text-area-transform'
import { selectNodeTransform } from './runtime/lib/core/transforms/select-transform'

// Module options TypeScript interface definition
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface CXModuleOptions {}

export default defineNuxtModule<CXModuleOptions>({
  meta: {
    name: 'chemical-x-forms',
    configKey: 'chemicalX',
    compatibility: {
      nuxt: '>=3.0.0',
    },
  },
  defaults: {},
  setup(_options, nuxt) {
    nuxt.options.vue.compilerOptions.nodeTransforms ??= []
    nuxt.options.vue.compilerOptions.nodeTransforms.push(
      selectNodeTransform,
      inputTextAreaNodeTransform
    )

    // Auto-import `useForm` — the framework-agnostic core composable (same
    // binding as `@chemical-x/forms`'s top-level `useForm` export, which
    // is the abstract form composable). Consumers who want the zod-typed
    // wrapper must import from `@chemical-x/forms/zod` or `/zod-v3`
    // explicitly.
    //
    // We point at the public package entry rather than a relative
    // `./runtime/…` path on purpose: a relative path would cause Nuxt's
    // bundler to treat the file as a standalone module graph — producing
    // a second copy of the registry singleton, disjoint from the one
    // bundled into `@chemical-x/forms/zod`. Two copies ⇒ two registries
    // ⇒ `createChemicalXForms()` installs on one while `useForm({…})`
    // looks in the other, and every call throws `Registry not found`.
    // Importing from the package entry funnels every caller through the
    // shared chunk.
    addImports([{ name: 'useForm', from: '@chemical-x/forms' }])

    // Plugin that installs `createChemicalXForms()` on the Vue app and
    // wires the payload serialize/hydrate bridge. Emitted via
    // `addPluginTemplate` rather than shipping a `dist/runtime/plugins/…`
    // file for the same singleton reason: the template's imports resolve
    // through the consumer's normal node-resolution to the same bundled
    // `@chemical-x/forms` the rest of the app uses. Keeping the Nuxt-
    // specific hook wiring inside this template (and out of
    // `src/runtime/`) also preserves the bare-Vue path — nothing under
    // `src/runtime/core/**` imports `nuxt/app` or `#app`.
    //
    // `addPluginTemplate` defaults to PREPEND so the plugin runs before
    // any user plugin / page; `enforce: 'pre'` in the plugin body makes
    // that ordering explicit at the Nuxt-plugin layer too. Together
    // they guarantee the registry is installed (and SSR payload staged
    // into `pendingHydration`) before any `useForm` call runs.
    addPluginTemplate({
      filename: 'chemical-x-forms.plugin.mjs',
      getContents: () => `
import { defineNuxtPlugin } from '#app'
import { createChemicalXForms, hydrateChemicalXState, renderChemicalXState } from '@chemical-x/forms'

export default defineNuxtPlugin({
  name: 'chemical-x-forms',
  enforce: 'pre',
  setup(nuxtApp) {
    const isServer = import.meta.server
    nuxtApp.vueApp.use(createChemicalXForms({ override: isServer }))

    if (isServer) {
      nuxtApp.hook('app:rendered', () => {
        nuxtApp.payload.chemicalX = renderChemicalXState(nuxtApp.vueApp)
      })
    } else if (nuxtApp.payload.chemicalX !== undefined) {
      hydrateChemicalXState(nuxtApp.vueApp, nuxtApp.payload.chemicalX)
    }
  },
})
`,
    })

    // v-register directive type. The directive itself is globally
    // registered by `createChemicalXForms().install(app)` in the plugin
    // above; this template only publishes the type so that
    // `<input v-register="…">` type-checks in consumer SFCs.
    addTypeTemplate({
      filename: 'types/v-register.d.ts',
      getContents: () => `// Generated by @chemical-x/forms
import type { ObjectDirective } from "vue"
import type { RegisterDirective } from "@chemical-x/forms/types"

declare module "vue" {
  interface GlobalDirectives {
    vRegister: RegisterDirective
  }
}

export { }`,
    })
  },
})
