name: Node.js Compatibility Matrix
run-name: Node.js Compatibility Matrix

on:
  push:
    branches: ["**"] # Run on every branch push
  pull_request:
    branches: ["**"] # Run on every PR regardless of target branch

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["lts/*", 16, 18, 20, 22]
      fail-fast: false # Run all jobs even if one fails

    name: Node.js ${{ matrix.node-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          # Use your lockfile as a cache dependency to speed up installs
          cache-dependency-path: "**/pnpm-lock.yaml"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.7.0 # Specify your desired pnpm version

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
