name: Publish to NPM and Version Bump

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      version_type:
        description: "Version type (major, minor, patch)"
        required: true
        default: "patch"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org/"
          always-auth: true

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Validate Auth
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run tests
        run: pnpm test

      - name: Configure Git identity
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Bump version
        id: version_bump
        run: |
          if [ -z "${{ github.event.inputs.version_type }}" ]; then
            pnpm version patch
          else
            pnpm version ${{ github.event.inputs.version_type }}
          fi

      - name: Stash version bump (for rollback)
        run: git stash push -m "Stash version bump"
        if: always() # Always stash after the version bump, even if it fails

      - name: Build
        run: pnpm prepack

      - name: Publish to npm
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push version bump
        run: git push --follow-tags
        if: success()

      - name: Rollback version bump if failed
        if: failure()
        run: |
          echo "Rolling back version bump due to failure..."
          git reset --hard HEAD~1  # Reset to the previous commit
