name: Publish to NPM and Version Bump
run-name: Publish ${{ github.event.inputs.version_type }} release to NPM and Version Bump
on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Version type (major, minor, patch)"
        required: true
        default: "patch"
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate next version
        id: calculate-next-version
        run: |
          CURRENT=$(node -p "require('./package.json').version")
          # Using semver.org compliant version incrementing
          if [ "${{ github.event.inputs.version_type }}" = "major" ]; then
            NEXT=$(echo $CURRENT | awk -F. '{print $1+1".0.0"}')
          elif [ "${{ github.event.inputs.version_type }}" = "minor" ]; then
            NEXT=$(echo $CURRENT | awk -F. '{print $1"."$2+1".0"}')
          else
            NEXT=$(echo $CURRENT | awk -F. '{print $1"."$2"."$3+1}')
          fi
          echo "next_version=$NEXT" >> $GITHUB_OUTPUT
          echo "WORKFLOW_TITLE=Publish ${{ github.event.inputs.version_type }} release to NPM (v. $NEXT)" >> $GITHUB_ENV

      - name: Update version
        run: echo "::notice title=Version::Publishing version ${{ steps.calculate-next-version.outputs.next_version }}"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org/"
          always-auth: true

      - name: Install pnpm
        run: npm install -g pnpm@9.7.0

      - name: Install dependencies
        run: pnpm install

      - name: Validate Auth
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run tests
        run: pnpm test

      - name: Configure Git identity
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Bump version
        run: |
          if [ -z "${{ github.event.inputs.version_type }}" ]; then
            pnpm version patch
          else
            pnpm version ${{ github.event.inputs.version_type }}
          fi

      - name: Build
        run: pnpm prepack

      - name: Publish to npm
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push version bump
        if: success()
        run: git push --follow-tags

      - name: Rollback version bump if failed
        if: failure()
        run: |
          echo "Rolling back version bump due to failure..."
          git reset --hard HEAD~1
