name: Publish to NPM and Version Bump

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      version_type:
        description: "Version type (major, minor, patch)"
        required: true
        default: "patch"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Full git history so we can push commits/tags

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23
          registry-url: "https://registry.npmjs.org/"
          always-auth: true

      - name: Install pnpm
        run: npm install -g pnpm@9.7.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate Auth
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run tests
        run: pnpm test

      - name: \[Debug\] Check git status before version bump
        run: |
          echo "DEBUG: Checking for uncommitted changes before bump..."
          git status
          git diff --name-only

      - name: Configure Git identity
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Bump version
        run: |
          if [ -z "${{ github.event.inputs.version_type }}" ]; then
            pnpm version patch
          else
            pnpm version ${{ github.event.inputs.version_type }}
          fi

      - name: Build
        run: pnpm prepack

      - name: Publish to npm
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push version bump
        if: success()
        run: git push --follow-tags

      - name: Rollback version bump if failed
        if: failure()
        run: |
          echo "Rolling back version bump due to failure..."
          git reset --hard HEAD~1
